# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

sudo: required

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

warnings_are_errors: false

notifications:
  email:
    on_success: enrique.audain@gmail.com
    on_failure: enrique.audain@gmail.com
